// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA240Sj_XUL9k5B8r1bkgHgHHuNyZczm0A',
    appId: '1:786991309098:web:87bc17c883abb3dc39fe53',
    messagingSenderId: '786991309098',
    projectId: 'flutter-pig',
    authDomain: 'flutter-pig.firebaseapp.com',
    storageBucket: 'flutter-pig.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKceb7aZbggyc27gaEYl-uuZAqJXMYMNU',
    appId: '1:786991309098:android:9b43ca39464a792a39fe53',
    messagingSenderId: '786991309098',
    projectId: 'flutter-pig',
    storageBucket: 'flutter-pig.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJXvUIG6Ht3o639Lx_p7YSZvMtI-c6Nzs',
    appId: '1:786991309098:ios:e6c5198c1263df8039fe53',
    messagingSenderId: '786991309098',
    projectId: 'flutter-pig',
    storageBucket: 'flutter-pig.appspot.com',
    iosBundleId: 'com.example.scscpig',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJXvUIG6Ht3o639Lx_p7YSZvMtI-c6Nzs',
    appId: '1:786991309098:ios:3ac7f6abc34e7dbf39fe53',
    messagingSenderId: '786991309098',
    projectId: 'flutter-pig',
    storageBucket: 'flutter-pig.appspot.com',
    iosBundleId: 'com.example.scscpig.RunnerTests',
  );
}
